import "./globals.css";
import Header from "./component/header";
import Footer from "./component/footer";
import Providers from "./themes/themeProvider";
export const metadata = {
  title: "YUNA Portfolio",
  description: "Generated by yuna moon",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
